Repository wecode-bootcamp-korea/48-3rd-GypPT-frontend, pull requests merged in 2023-09, with the labels that each got.

#5 [배정완] 회원가입 페이지 레이아웃 구현 및 리팩토링 완료 / 리뷰 반영 완료
  public/data/data.json
  src/pages/SignUp/SignUp.jsx
  src/pages/SignUp/SignUp.scss
  src/pages/SignUp/components/Button/Button.jsx
  src/pages/SignUp/components/Button/Button.scss
  src/pages/SignUp/components/FormItem/FormItem.jsx
  src/pages/SignUp/components/Input/Input.jsx
  src/pages/SignUp/components/Input/Input.scss
  src/pages/SignUp/inputData.js
  src/styles/common.scss
Labels: 멘토 리뷰 요청, 추가 기능 구현 중

#3 [전미혜] 리뷰 반영 수정
  package-lock.json
  package.json
  public/data/getMembershipData.json
  public/data/personalTrainingData.json
  public/data/trainerProfile.json
  public/images/diet1.jpg
  public/images/diet2.jpg
  public/images/diet3.jpg
  public/images/exercise1.jpg
  public/images/exercise2.jpg
  public/images/exercise3.jpg
  public/images/trainer1.jpg
  public/images/trainer2.jpg
  public/images/trainer3.jpg
  public/images/trainer4.jpg
  src/API/getTrainerProfile.js
  src/components/ButtonM/ButtonM.jsx
  src/components/ButtonM/ButtonM.scss
  src/components/ButtonS/ButtonS.jsx
  src/components/ButtonS/ButtonS.scss
  src/components/ContentTab/ContentTab.jsx
  src/pages/PersonalTraining/PersonalTraining.jsx
  src/pages/PersonalTraining/PersonalTraining.scss
  src/pages/PersonalTraining/components/CheckBox/CheckBox.jsx
  src/pages/PersonalTraining/components/CheckBox/CheckBox.scss
  src/pages/PersonalTraining/components/DaysUntilStart/DaysUntilStart.jsx
  src/pages/PersonalTraining/components/DaysUntilStart/DaysUntilStart.scss
  src/pages/PersonalTraining/components/MyDietList/MyDietList.jsx
  src/pages/PersonalTraining/components/MyDietList/MyDietList.scss
  src/pages/PersonalTraining/components/MyExerciseList/MyExerciseList.jsx
  src/pages/PersonalTraining/components/MyExerciseList/MyExerciseList.scss
  src/pages/PersonalTraining/components/PersonalTrainingBox/PersonalTrainingBox.jsx
  src/pages/PersonalTraining/components/PersonalTrainingBox/PersonalTrainingBox.scss
  src/pages/PersonalTraining/components/ProfileContainer/ProfileContainer.scss
  src/pages/PersonalTraining/components/ProfileContainer/Profilecontainer.jsx
  src/pages/PersonalTraining/components/ProfileListBox/ProfileListBox.jsx
  src/pages/PersonalTraining/components/ProfileListBox/ProfileListBox.scss
  src/pages/PersonalTraining/components/SelectStartDate/SelectStartDate.jsx
  src/pages/PersonalTraining/components/SelectStartDate/SelectStartDate.scss
  src/pages/PersonalTraining/components/WeekCalendar/WeekCalendar.jsx
  src/pages/PersonalTraining/components/WeekCalendar/WeekCalendar.scss
  src/styles/common.scss
  src/styles/variables.scss
Labels: 멘토 리뷰 요청, 완료

#13 [배정완] KaKao Social Login function complete (리뷰반영완료)
  package-lock.json
  package.json
  src/Router.js
  src/pages/PersonalTraining/components/CheckBox/CheckBox.scss
  src/pages/SignIn/Oath.jsx
  src/pages/SignIn/SignIn.jsx
  src/pages/SignIn/kakaoLoginData.js
  src/pages/SignUp/SignUp.jsx
  src/pages/SignUp/SignUp.scss
  src/pages/SignUp/components/Button/Button.jsx
  src/pages/SignUp/components/Button/Button.scss
  src/pages/SignUp/components/FormItem/FormItem.jsx
  src/pages/SignUp/components/Input/Input.jsx
  src/pages/SignUp/components/Input/Input.scss
  src/pages/SignUp/inputData.js
Labels: 멘토 리뷰 요청

#16 [정효은]Add: Community integration and Post-add integration
  public/data/communityData.json
  public/data/postUserData.json
  src/config.js
  src/pages/Community/Community.jsx
  src/pages/Community/Post.jsx
  src/pages/Community/Post.scss
  src/pages/Community/PostDetail.jsx
  src/pages/Community/components/CommunityList.jsx
  src/pages/Community/components/CommunityList.scss
  src/pages/Community/components/CommunityNav.scss
  src/pages/Community/components/PostDetailBox.jsx
  src/pages/Community/components/PostNav.jsx
  src/pages/Community/components/PostNav.scss
  src/pages/Community/components/PostUser.jsx
  src/pages/Community/components/PostUser.scss
Labels: 멘토 리뷰 요청

#15 [배정완] Add: payment function complete
  public/data/membershipData.json
  public/data/trainerData.json
  src/API/getMembershipData.js
  src/API/postPaymentData.js
  src/Router.js
  src/pages/Payment/Payment.jsx
  src/pages/Payment/Payment.scss
  src/pages/Payment/PaymentData.js
  src/pages/Payment/components/Button/Button.scss
  src/pages/Payment/components/ProfileContainer/ProfileContainer.jsx
  src/pages/Payment/components/ProfileContainer/ProfileContainer.scss
  src/pages/Payment/components/RadioButton/RadioButton.jsx
  src/pages/Payment/components/RadioButton/RadioButton.scss
  src/pages/Payment/components/RadioCard/RadioCard.jsx
  src/pages/Payment/components/RadioCard/RadioCard.scss
Labels: 멘토 리뷰 요청
